### ISSUE TITLE
setval修改建议

### ISSUE THREAD

**Issue by JohnYu588** [SUNYunZeng/ImitateVue#1]
需要对setval进行如下修改：
  setVal(value, $data, inputValue) {
    var length = value.split('.').length;
    var index = 0;
    value.split('.').reduce((data, current) => {
      index++;
      if (index === length) {
        data[current] = inputValue;
      } else {
        return data[current];
      }
    }, $data);
  },
否则无法遍历修改到表达式的最后一级

**Comment by SUNYunZeng** [comment]
对的，已改正。
setVal(expr, vm, inputValue){
        let exprs = expr.split('.'), len = exprs.length;
        exprs.reduce((data,currentVal, idx)=>{
            if(idx===len-1){
                data[currentVal] = inputValue;
            }else{
                return data[currentVal]
            }
        }, vm.$data)
    }
